version: '3.5'
services:
  laravel-vue-template2:
    container_name: laraveldev2
    
    build:
      context: ../
      dockerfile: ./Setup-Files/DOCKERFILE
      args:
        NODE_VERSION: 22
    
    image: laraveldev2:latest
    
    restart: always
    
    volumes:
      - ../Project-Files:/var/www/frontend
      - node_modules:/var/www/frontend/node_modules
    
    working_dir: /var/www/frontend
    
    ports:
      - "8000:80"
      - "5173:5173"
    
    environment:
      APP_URL: "https://localhost:8000"
      VITE_DEV_SERVER_URL: "http://localhost:5173"
      CHOKIDAR_USEPOLLING: "true"
      APP_ENV: local
      SESSION_DRIVER: file

volumes:
  node_modules: